version: '2'

services:
  mongodb-server:
    image: mongo
    container_name: mongodb-server
    restart: always
    ports:
      - "27017:27017"

#  es-server:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
#    container_name: es-server
#    environment:
#      - node.name=es01
#      - cluster.name=local-cluster
#      - bootstrap.memory_lock=true
#      - discovery.type=single-node
#    mem_limit: 5368709120 # 5 GB
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data01:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#    networks:
#      - microservices

  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "6066:6066"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"

  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    hostname: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"

  spark-worker-2:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    hostname: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"


#volumes:
#  data01:
#    driver: local